openapi: 3.0.3
info:
  title: Tramways Roadmaps API
  description: Tramways Roadmaps API
  version: 1.0.0
servers:
  - url: http://localhost:8762/tramways/rest/
paths:
  /projects/{projectId}/maps:
    post:
      summary: 'Creates a map'
      operationId: 'createMap'
      tags: [ 'projects' ]
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMapRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoadMap'
  /projects/{projectId}/maps/{mapId}:
    get:
      summary: 'Gets a map'
      operationId: 'getMap'
      tags: [ 'projects' ]
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
        - in: path
          name: mapId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoadMap'
    put:
      summary: 'Updates a map'
      operationId: 'updateMap'
      tags: [ 'projects' ]
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
        - in: path
          name: mapId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMapRequest'
      responses:
        '200':
          description: Ok
    delete:
      summary: 'Deletes a map'
      operationId: 'deleteMap'
      tags: [ 'projects' ]
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
        - in: path
          name: mapId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CreateMapRequest:
      type: object
      properties:
        map:
          $ref: '#/components/schemas/RoadMap'
    UpdateMapRequest:
      type: object
      properties:
        map:
          $ref: '#/components/schemas/RoadMap'
    RoadMapDescription:
      type: object
      properties:
        uuid:
          type: string
        name:
          type: string
    RoadMap:
      type: object
      properties:
        uuid:
          type: string
        name:
          type: string
        content:
          $ref: '#/components/schemas/RoadMapContent'
    RoadMapContent:
      type: object
      properties:
        points:
          type: array
          items:
            $ref: '#/components/schemas/RelevantPoint'
        lanes:
          type: array
          items:
            $ref: '#/components/schemas/Lane'
    RelevantPoint:
      allOf:
        - $ref: '#/components/schemas/Configurable'
        - type: object
          properties:
            links:
              type: array
              items:
                $ref: '#/components/schemas/CrossingLink'
    Lane:
      allOf:
        - $ref: '#/components/schemas/Configurable'
        - type: object
          properties:
            sourceId:
              type: string
            destinationId:
              type: string
    CrossingLink:
      allOf:
        - $ref: '#/components/schemas/Configurable'
        - type: object
          properties:
            sourceId:
              type: string
            destinationId:
              type: string
    Configurable:
      type: object
      discriminator:
        propertyName: 'configurableType'
      properties:
        id:
          type: string
        category:
          type: string
        configurableType:
          type: string
        props:
          type: array
          items:
            $ref: './properties.yaml#/components/schemas/Property'
security:
  - bearerAuth: [ ]
